# Generated by Django 6.0.2 on 2026-02-17 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retrieval', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchhistory',
            name='query_metrics_json',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='results_json',
            field=models.TextField(blank=True, default=''),
        ),
    ]
